version: "3"

services:
  db:
    container_name: quiz_db
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_USER: username
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: quiz_app
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PORT: 3306
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./quiz-data.sql:/docker-entrypoint-initdb.d/create_database.sql
    networks:
      - app-network

  app:
    container_name: quiz_app
    build:
      context: ./app
    ports:
      - "3000:3000"
    env_file: "./app/.env"
    depends_on:
      - server
    networks:
      - app-network

  server:
    container_name: quiz_server
    build:
      context: ./server
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=quiz_db
      - DB_USER=username
      - DB_PASSWORD=pass
      - DB_NAME=quiz_app
    depends_on:
      - db
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge
